#!/usr/bin/env python3
"""
Generate Missing Visualizations:
1. Wasserstein distance heatmaps
2. Weighted persistence analysis

USAGE:
    Run this AFTER main1.py has completed and generated the CSV files.
    
    python3 generate_missing_visualizations_UPDATED.py
    
REQUIREMENTS:
    - main1.py must have completed successfully
    - three_stage_comparisons.csv must exist in results directory
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import sys

# ============================================================================
# CONFIGURATION - UPDATE THESE PATHS TO MATCH YOUR SETUP
# ============================================================================

# Path to your results directory (where main1.py saves outputs)
# Default: TDA_Results27102025V1 (from main1.py line 1130)
RESULTS_DIR = Path("TDA_Results27102025V1")

# CSV file generated by main1.py (line 841)
CSV_FILE = RESULTS_DIR / "three_stage_comparisons.csv"

# Output directory for visualizations
OUTPUT_DIR = RESULTS_DIR / "additional_visualizations"

# ============================================================================
# VALIDATION
# ============================================================================

print("=" * 70)
print("WASSERSTEIN & WEIGHTED PERSISTENCE ANALYSIS")
print("=" * 70)

# Check if CSV exists
if not CSV_FILE.exists():
    print(f"\n❌ ERROR: CSV file not found!")
    print(f"   Expected: {CSV_FILE}")
    print(f"\n   Please run main1.py first to generate the data.")
    print(f"   Or update RESULTS_DIR and CSV_FILE paths in this script.")
    sys.exit(1)

print(f"\n✅ Found CSV: {CSV_FILE}")

# Create output directory
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
print(f"✅ Output directory: {OUTPUT_DIR}")

# ============================================================================
# LOAD DATA
# ============================================================================

print("\n📊 Loading data...")
df = pd.read_csv(CSV_FILE)
print(f"   Loaded {len(df)} rows")
print(f"   Columns: {', '.join(df.columns[:5])}...")

# ============================================================================
# 1. WEIGHTED PERSISTENCE ANALYSIS
# ============================================================================
print("\n" + "=" * 70)
print("1. WEIGHTED PERSISTENCE ANALYSIS")
print("=" * 70)

# Filter for 5% noise level
df_05 = df[df['noise_level'] == 0.05]
print(f"   Filtered to noise_level=0.05: {len(df_05)} rows")

weighted_results = []
for noise_type in ['gaussian', 'salt_pepper']:
    df_noise = df_05[df_05['noise_type'] == noise_type]
    
    # Weighted impact = Wasserstein distance (already persistence-weighted)
    weighted_h0 = df_noise['wasserstein_clean_noisy_H0'].mean()
    weighted_h1 = df_noise['wasserstein_clean_noisy_H1'].mean()
    
    # Unweighted impact = raw feature count
    unweighted = df_noise['noise_impact_total'].mean()
    
    weighted_results.append({
        'noise_type': noise_type,
        'unweighted_impact': unweighted,
        'weighted_h0': weighted_h0,
        'weighted_h1': weighted_h1,
        'weighted_total': weighted_h0 + weighted_h1
    })

weighted_df = pd.DataFrame(weighted_results)

# Calculate ratios
gaussian_weighted = weighted_df[weighted_df['noise_type'] == 'gaussian']['weighted_total'].values[0]
saltpepper_weighted = weighted_df[weighted_df['noise_type'] == 'salt_pepper']['weighted_total'].values[0]
weighted_ratio = saltpepper_weighted / gaussian_weighted

gaussian_unweighted = weighted_df[weighted_df['noise_type'] == 'gaussian']['unweighted_impact'].values[0]
saltpepper_unweighted = weighted_df[weighted_df['noise_type'] == 'salt_pepper']['unweighted_impact'].values[0]
unweighted_ratio = saltpepper_unweighted / gaussian_unweighted

print(f"\n📈 RESULTS:")
print(f"   Unweighted ratio (feature count): {unweighted_ratio:.2f}×")
print(f"   Weighted ratio (Wasserstein):     {weighted_ratio:.2f}×")
print(f"   Difference: {abs(weighted_ratio - unweighted_ratio):.2f}×")

# Visualization: Weighted vs Unweighted
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Unweighted
ax = axes[0]
x = ['Gaussian', 'Salt-Pepper']
y = [gaussian_unweighted, saltpepper_unweighted]
bars = ax.bar(x, y, color=['#3498db', '#e74c3c'], alpha=0.7, edgecolor='black', linewidth=1.5)
ax.set_ylabel('Feature Count Change', fontsize=12, fontweight='bold')
ax.set_title('Unweighted Impact\n(Raw Feature Count)', fontsize=13, fontweight='bold')
ax.set_ylim(0, max(y) * 1.2)
for bar, val in zip(bars, y):
    ax.text(bar.get_x() + bar.get_width()/2, val + max(y)*0.02, 
            f'{val:,.0f}', ha='center', va='bottom', fontsize=11, fontweight='bold')
ax.text(0.5, max(y) * 1.1, f'Ratio: {unweighted_ratio:.2f}×', 
        ha='center', fontsize=12, fontweight='bold', 
        bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
ax.grid(axis='y', alpha=0.3, linestyle='--')

# Weighted
ax = axes[1]
y = [gaussian_weighted, saltpepper_weighted]
bars = ax.bar(x, y, color=['#3498db', '#e74c3c'], alpha=0.7, edgecolor='black', linewidth=1.5)
ax.set_ylabel('Wasserstein Distance', fontsize=12, fontweight='bold')
ax.set_title('Weighted Impact\n(Persistence-Weighted via Wasserstein)', fontsize=13, fontweight='bold')
ax.set_ylim(0, max(y) * 1.2)
for bar, val in zip(bars, y):
    ax.text(bar.get_x() + bar.get_width()/2, val + max(y)*0.02, 
            f'{val:.1f}', ha='center', va='bottom', fontsize=11, fontweight='bold')
ax.text(0.5, max(y) * 1.1, f'Ratio: {weighted_ratio:.2f}×', 
        ha='center', fontsize=12, fontweight='bold',
        bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
ax.grid(axis='y', alpha=0.3, linestyle='--')

plt.suptitle('Weighted vs Unweighted Topological Impact (5% Noise)', 
             fontsize=15, fontweight='bold', y=1.02)
plt.tight_layout()
output_file = OUTPUT_DIR / 'weighted_vs_unweighted_comparison.png'
plt.savefig(output_file, dpi=300, bbox_inches='tight')
print(f"\n✅ Saved: {output_file}")
plt.close()

# ============================================================================
# 2. WASSERSTEIN DISTANCE HEATMAPS
# ============================================================================
print("\n" + "=" * 70)
print("2. WASSERSTEIN DISTANCE HEATMAPS")
print("=" * 70)

# Heatmap 1: Wasserstein H0 by noise type and level
pivot_h0 = df.pivot_table(
    values='wasserstein_clean_noisy_H0',
    index='noise_type',
    columns='noise_level',
    aggfunc='mean'
)

fig, axes = plt.subplots(1, 2, figsize=(16, 5))

# H0 Heatmap
ax = axes[0]
sns.heatmap(pivot_h0, annot=True, fmt='.1f', cmap='YlOrRd', 
            cbar_kws={'label': 'Wasserstein Distance'}, ax=ax,
            linewidths=1, linecolor='black',annot_kws={'size': 16})
ax.tick_params(labelsize=14)
ax.set_title('Wasserstein H₀ Distance\n(Connected Components)', 
             fontsize=13, fontweight='bold')
ax.set_xlabel('Noise Level', fontsize=16, fontweight='bold')
ax.set_ylabel('Noise Type', fontsize=16, fontweight='bold')
ax.set_yticklabels(['Gaussian', 'Salt-Pepper'], rotation=0)

# H1 Heatmap
pivot_h1 = df.pivot_table(
    values='wasserstein_clean_noisy_H1',
    index='noise_type',
    columns='noise_level',
    aggfunc='mean'
)

ax = axes[1]
sns.heatmap(pivot_h1, annot=True, fmt='.1f', cmap='YlGnBu',
            cbar_kws={'label': 'Wasserstein Distance'}, ax=ax,
            linewidths=1, linecolor='black',annot_kws={'size': 16})
ax.tick_params(labelsize=14)
ax.set_title('Wasserstein H₁ Distance\n(Topological Holes)', 
             fontsize=13, fontweight='bold')
ax.set_xlabel('Noise Level', fontsize=16, fontweight='bold')
ax.set_ylabel('Noise Type', fontsize=16, fontweight='bold')
ax.set_yticklabels(['Gaussian', 'Salt-Pepper'], rotation=0)

plt.suptitle('Wasserstein Distance Heatmaps: Noise Impact on Topology',
             fontsize=15, fontweight='bold', y=1.02)
plt.tight_layout()
output_file = OUTPUT_DIR / 'wasserstein_heatmaps_by_noise.png'
plt.savefig(output_file, dpi=300, bbox_inches='tight')
print(f"✅ Saved: {output_file}")
plt.close()

# Heatmap 2: Recovery effectiveness (Clean→Denoised Wasserstein)
pivot_recovery_h0 = df.pivot_table(
    values='wasserstein_clean_denoised_H0',
    index='denoise_method',
    columns='noise_type',
    aggfunc='mean'
)

pivot_recovery_h1 = df.pivot_table(
    values='wasserstein_clean_denoised_H1',
    index='denoise_method',
    columns='noise_type',
    aggfunc='mean'
)

fig, axes = plt.subplots(1, 2, figsize=(14, 7))

# Recovery H0
ax = axes[0]
sns.heatmap(pivot_recovery_h0, annot=True, fmt='.1f', cmap='RdYlGn_r',
            cbar_kws={'label': 'Wasserstein Distance\n(Lower = Better Recovery)'},
            ax=ax, linewidths=1, linecolor='black',annot_kws={'size': 16})
ax.tick_params(labelsize=14)
ax.set_title('Denoising Recovery: H₀\n(Lower Distance = Better)', 
             fontsize=13, fontweight='bold')
ax.set_xlabel('Noise Type', fontsize=16, fontweight='bold')
ax.set_ylabel('Denoising Method', fontsize=16, fontweight='bold')
ax.set_xticklabels(['Gaussian', 'Salt-Pepper'], rotation=0)

# Recovery H1
ax = axes[1]
sns.heatmap(pivot_recovery_h1, annot=True, fmt='.1f', cmap='RdYlGn_r',
            cbar_kws={'label': 'Wasserstein Distance\n(Lower = Better Recovery)'},
            ax=ax, linewidths=1, linecolor='black',annot_kws={'size': 16})
ax.tick_params(labelsize=14)
ax.set_title('Denoising Recovery: H₁\n(Lower Distance = Better)', 
             fontsize=13, fontweight='bold')
ax.set_xlabel('Noise Type', fontsize=16, fontweight='bold')
ax.set_ylabel('Denoising Method', fontsize=16, fontweight='bold')
ax.set_xticklabels(['Gaussian', 'Salt-Pepper'], rotation=0)

plt.suptitle('Denoising Recovery Effectiveness (Wasserstein Distance from Clean)',
             fontsize=15, fontweight='bold', y=1.00)
plt.tight_layout()
output_file = OUTPUT_DIR / 'wasserstein_recovery_heatmaps.png'
plt.savefig(output_file, dpi=300, bbox_inches='tight')
print(f"✅ Saved: {output_file}")
plt.close()

# ============================================================================
# 3. COMPREHENSIVE RATIO SUMMARY
# ============================================================================
print("\n" + "=" * 70)
print("3. COMPREHENSIVE RATIO SUMMARY")
print("=" * 70)

ratio_summary = {
    'Metric': [
        'Feature Count (Total)',
        'Wasserstein H₀',
        'Wasserstein H₁',
        'Wasserstein Combined',
        'Betti β₀ Change',
        'Betti β₁ Change'
    ],
    'Gaussian (5%)': [],
    'Salt-Pepper (5%)': [],
    'Ratio (SP/G)': []
}

# Calculate each metric
metrics = [
    ('noise_impact_total', 'Feature Count (Total)'),
    ('wasserstein_clean_noisy_H0', 'Wasserstein H₀'),
    ('wasserstein_clean_noisy_H1', 'Wasserstein H₁'),
    (None, 'Wasserstein Combined'),  # Special case
    ('noise_impact_betti_0', 'Betti β₀ Change'),
    ('noise_impact_betti_1', 'Betti β₁ Change')
]

for metric_col, metric_name in metrics:
    if metric_col is None:  # Combined Wasserstein
        g_val = df_05[df_05['noise_type'] == 'gaussian']['wasserstein_clean_noisy_H0'].mean() + \
                df_05[df_05['noise_type'] == 'gaussian']['wasserstein_clean_noisy_H1'].mean()
        sp_val = df_05[df_05['noise_type'] == 'salt_pepper']['wasserstein_clean_noisy_H0'].mean() + \
                 df_05[df_05['noise_type'] == 'salt_pepper']['wasserstein_clean_noisy_H1'].mean()
    else:
        g_val = df_05[df_05['noise_type'] == 'gaussian'][metric_col].mean()
        sp_val = df_05[df_05['noise_type'] == 'salt_pepper'][metric_col].mean()
    
    ratio = sp_val / g_val if g_val > 0 else 0
    
    ratio_summary['Gaussian (5%)'].append(f'{g_val:,.1f}')
    ratio_summary['Salt-Pepper (5%)'].append(f'{sp_val:,.1f}')
    ratio_summary['Ratio (SP/G)'].append(f'{ratio:.2f}×')

ratio_df = pd.DataFrame(ratio_summary)
output_file = OUTPUT_DIR / 'comprehensive_ratio_summary.csv'
ratio_df.to_csv(output_file, index=False)
print(f"✅ Saved: {output_file}")

# Pretty print
print("\n" + "=" * 70)
print("COMPREHENSIVE RATIO SUMMARY (5% Noise Level)")
print("=" * 70)
print(ratio_df.to_string(index=False))
print("=" * 70)

# Save weighted persistence results
output_file = OUTPUT_DIR / 'weighted_persistence_analysis.csv'
weighted_df.to_csv(output_file, index=False)
print(f"\n✅ Saved: {output_file}")

# ============================================================================
# SUMMARY
# ============================================================================
print("\n" + "=" * 70)
print("✅ ALL VISUALIZATIONS GENERATED!")
print("=" * 70)
print(f"\nOutput directory: {OUTPUT_DIR}")
print("\nGenerated files:")
print("  1. weighted_vs_unweighted_comparison.png")
print("  2. wasserstein_heatmaps_by_noise.png")
print("  3. wasserstein_recovery_heatmaps.png")
print("  4. comprehensive_ratio_summary.csv")
print("  5. weighted_persistence_analysis.csv")
print("\n" + "=" * 70)
print(f"📊 THE ONE TRUE RATIO: {weighted_ratio:.1f}×")
print("   (Salt-pepper causes {:.1f}× more disruption than Gaussian)".format(weighted_ratio))
print("=" * 70)

