name: nucmm_zebrafish
path: data/raw_data/nucmm/Zebrafish (NucMM-Z)/zebrafish
file_extension: .png
color_mode: grayscale
invert: false
resize: null
threshold: otsu
roi: null
notes: "Zebrafish subset from NucMM dataset"
