name: nucmm_mouse
path: "${DATA_PATH}/raw_data/nucmm/Mouse (NucMM-M)/mouse"
file_extension: .png
color_mode: grayscale
invert: false
resize: null
threshold: otsu
roi: null
notes: "Mouse subset from NucMM dataset"


